# Generated by Django 6.0.1 on 2026-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ithute', '0002_ticket_solved_at_ticket_solved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_key_pem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature_method',
            field=models.CharField(default='rsa', max_length=20),
        ),
    ]
